export type Section = "docs" | "reference";

export type Entry = {
  source: string;
  slug: string;
  section: Section;
  group: string | null;
  route: string;
  title: string;
  description: string | null;
  canonical: string | null;
  legacy: string[];
};

export const ENTRIES: Entry[] = [
  {
    source: "index.mdx",
    slug: "index",
    section: "docs",
    group: null,
    route: "/docs",
    title: "systemg",
    description: "An agent-friendly general process composer.",
    canonical: null,
    legacy: ["/docs/index", "/index"],
  },
  {
    source: "intro.mdx",
    slug: "intro",
    section: "docs",
    group: null,
    route: "/docs/intro",
    title: "Introduction",
    description: null,
    canonical: null,
    legacy: ["/intro"],
  },
  {
    source: "installation.mdx",
    slug: "installation",
    section: "docs",
    group: "Installation",
    route: "/docs/installation",
    title: "Installation",
    description: null,
    canonical: null,
    legacy: ["/installation"],
  },
  {
    source: "installation/upgrading.mdx",
    slug: "installation/upgrading",
    section: "docs",
    group: "Installation",
    route: "/docs/installation/upgrading",
    title: "Upgrading sysg",
    description: null,
    canonical: null,
    legacy: ["/installation/upgrading"],
  },
  {
    source: "quickstart.mdx",
    slug: "quickstart",
    section: "docs",
    group: null,
    route: "/docs/quickstart",
    title: "Quickstart",
    description: null,
    canonical: null,
    legacy: ["/quickstart"],
  },
  {
    source: "how-it-works/index.mdx",
    slug: "how-it-works",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works",
    title: "How It Works",
    description: null,
    canonical: null,
    legacy: ["/how-it-works"],
  },
  {
    source: "how-it-works/configuration.mdx",
    slug: "how-it-works/configuration",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works/configuration",
    title: "Configuration",
    description: null,
    canonical: null,
    legacy: ["/how-it-works/configuration"],
  },
  {
    source: "how-it-works/projects.mdx",
    slug: "how-it-works/projects",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works/projects",
    title: "Projects",
    description: null,
    canonical: null,
    legacy: ["/how-it-works/projects"],
  },
  {
    source: "how-it-works/cron.mdx",
    slug: "how-it-works/cron",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works/cron",
    title: "Cron",
    description: null,
    canonical: null,
    legacy: ["/how-it-works/cron"],
  },
  {
    source: "how-it-works/hooks.mdx",
    slug: "how-it-works/hooks",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works/hooks",
    title: "Hooks",
    description: null,
    canonical: null,
    legacy: ["/how-it-works/hooks"],
  },
  {
    source: "how-it-works/state.mdx",
    slug: "how-it-works/state",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works/state",
    title: "State",
    description: null,
    canonical: null,
    legacy: ["/how-it-works/state"],
  },
  {
    source: "how-it-works/logs.mdx",
    slug: "how-it-works/logs",
    section: "docs",
    group: "How It Works",
    route: "/docs/how-it-works/logs",
    title: "Logs",
    description: null,
    canonical: null,
    legacy: ["/how-it-works/logs"],
  },
  {
    source: "kernel-mode/index.mdx",
    slug: "kernel-mode",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode",
    title: "Kernel Mode",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode"],
  },
  {
    source: "kernel-mode/how-sysg-meets-the-kernel.mdx",
    slug: "kernel-mode/how-sysg-meets-the-kernel",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode/how-sysg-meets-the-kernel",
    title: "How sysg Meets the Kernel",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode/how-sysg-meets-the-kernel"],
  },
  {
    source: "kernel-mode/system-mode.mdx",
    slug: "kernel-mode/system-mode",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode/system-mode",
    title: "System Mode",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode/system-mode"],
  },
  {
    source: "kernel-mode/container-init.mdx",
    slug: "kernel-mode/container-init",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode/container-init",
    title: "Container-Init (PID 1)",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode/container-init"],
  },
  {
    source: "kernel-mode/sandboxing.mdx",
    slug: "kernel-mode/sandboxing",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode/sandboxing",
    title: "Kernel-Enforced Sandboxing",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode/sandboxing"],
  },
  {
    source: "kernel-mode/kernel-assisted.mdx",
    slug: "kernel-mode/kernel-assisted",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode/kernel-assisted",
    title: "Kernel-Assisted Observation",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode/kernel-assisted"],
  },
  {
    source: "kernel-mode/security.mdx",
    slug: "kernel-mode/security",
    section: "docs",
    group: "Kernel Mode",
    route: "/docs/kernel-mode/security",
    title: "Security & Audits",
    description: null,
    canonical: null,
    legacy: ["/kernel-mode/security"],
  },
  {
    source: "security.mdx",
    slug: "security",
    section: "docs",
    group: null,
    route: "/docs/security",
    title: "Security",
    description: null,
    canonical: null,
    legacy: ["/security"],
  },
  {
    source: "philosophy.mdx",
    slug: "philosophy",
    section: "docs",
    group: null,
    route: "/docs/philosophy",
    title: "Philosophy",
    description: null,
    canonical: null,
    legacy: ["/philosophy"],
  },
  {
    source: "examples/index.mdx",
    slug: "examples",
    section: "docs",
    group: "Examples",
    route: "/docs/examples",
    title: "Examples",
    description: null,
    canonical: null,
    legacy: ["/examples"],
  },
  {
    source: "examples/hello-world.mdx",
    slug: "examples/hello-world",
    section: "docs",
    group: "Examples",
    route: "/docs/examples/hello-world",
    title: "Hello World",
    description: null,
    canonical: null,
    legacy: ["/examples/hello-world"],
  },
  {
    source: "examples/crud.mdx",
    slug: "examples/crud",
    section: "docs",
    group: "Examples",
    route: "/docs/examples/crud",
    title: "CRUD Application",
    description: null,
    canonical: null,
    legacy: ["/examples/crud"],
  },
  {
    source: "examples/units.mdx",
    slug: "examples/units",
    section: "docs",
    group: "Examples",
    route: "/docs/examples/units",
    title: "Units",
    description: null,
    canonical: null,
    legacy: ["/examples/units"],
  },
  {
    source: "examples/orchestrator.mdx",
    slug: "examples/orchestrator",
    section: "docs",
    group: "Examples",
    route: "/docs/examples/orchestrator",
    title: "Orchestrator",
    description: null,
    canonical: null,
    legacy: ["/examples/orchestrator"],
  },
  {
    source: "integrations/claude-code.mdx",
    slug: "integrations/claude-code",
    section: "docs",
    group: "Integrations",
    route: "/docs/integrations/claude-code",
    title: "Claude Code",
    description: null,
    canonical: null,
    legacy: ["/integrations/claude-code"],
  },
  {
    source: "how-it-works/configuration.mdx",
    slug: "how-it-works/configuration",
    section: "reference",
    group: "Configuration",
    route: "/reference/configuration",
    title: "Configuration",
    description: null,
    canonical: "/docs/how-it-works/configuration",
    legacy: [],
  },
  {
    source: "how-it-works/commands/index.mdx",
    slug: "how-it-works/commands",
    section: "reference",
    group: "Commands",
    route: "/reference/commands",
    title: "Commands",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands", "/how-it-works/commands"],
  },
  {
    source: "how-it-works/commands/start.mdx",
    slug: "how-it-works/commands/start",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/start",
    title: "start",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/start", "/how-it-works/commands/start"],
  },
  {
    source: "how-it-works/commands/stop.mdx",
    slug: "how-it-works/commands/stop",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/stop",
    title: "stop",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/stop", "/how-it-works/commands/stop"],
  },
  {
    source: "how-it-works/commands/restart.mdx",
    slug: "how-it-works/commands/restart",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/restart",
    title: "restart",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/restart", "/how-it-works/commands/restart"],
  },
  {
    source: "how-it-works/commands/logs.mdx",
    slug: "how-it-works/commands/logs",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/logs",
    title: "logs",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/logs", "/how-it-works/commands/logs"],
  },
  {
    source: "how-it-works/commands/status.mdx",
    slug: "how-it-works/commands/status",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/status",
    title: "status",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/status", "/how-it-works/commands/status"],
  },
  {
    source: "how-it-works/commands/inspect.mdx",
    slug: "how-it-works/commands/inspect",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/inspect",
    title: "inspect",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/inspect", "/how-it-works/commands/inspect"],
  },
  {
    source: "how-it-works/commands/validate.mdx",
    slug: "how-it-works/commands/validate",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/validate",
    title: "validate",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/validate", "/how-it-works/commands/validate"],
  },
  {
    source: "how-it-works/commands/migrate.mdx",
    slug: "how-it-works/commands/migrate",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/migrate",
    title: "migrate",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/migrate", "/how-it-works/commands/migrate"],
  },
  {
    source: "how-it-works/commands/migrate-state.mdx",
    slug: "how-it-works/commands/migrate-state",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/migrate-state",
    title: "migrate-state",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/migrate-state", "/how-it-works/commands/migrate-state"],
  },
  {
    source: "how-it-works/commands/purge.mdx",
    slug: "how-it-works/commands/purge",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/purge",
    title: "purge",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/purge", "/how-it-works/commands/purge"],
  },
  {
    source: "how-it-works/commands/version.mdx",
    slug: "how-it-works/commands/version",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/version",
    title: "version",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/version", "/how-it-works/commands/version"],
  },
  {
    source: "how-it-works/commands/spawn.mdx",
    slug: "how-it-works/commands/spawn",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/spawn",
    title: "spawn",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/spawn", "/how-it-works/commands/spawn"],
  },
  {
    source: "how-it-works/commands/start-vs-spawn.mdx",
    slug: "how-it-works/commands/start-vs-spawn",
    section: "reference",
    group: "Commands",
    route: "/reference/commands/start-vs-spawn",
    title: "Start vs Spawn",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/commands/start-vs-spawn", "/how-it-works/commands/start-vs-spawn"],
  },
  {
    source: "how-it-works/dialog/index.mdx",
    slug: "how-it-works/dialog",
    section: "reference",
    group: "Dialog",
    route: "/reference/dialog",
    title: "Dialog",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/dialog", "/how-it-works/dialog"],
  },
  {
    source: "how-it-works/dialog/codes.mdx",
    slug: "how-it-works/dialog/codes",
    section: "reference",
    group: "Dialog",
    route: "/reference/dialog/codes",
    title: "Codes",
    description: null,
    canonical: null,
    legacy: ["/docs/how-it-works/dialog/codes", "/how-it-works/dialog/codes"],
  },
];

export const BY_ROUTE = new Map(ENTRIES.map((e) => [e.route, e]));

export const REDIRECTS = ENTRIES.flatMap((e) => e.legacy.map((from) => ({ from, to: e.route })));
