import { createSystem, defaultBaseConfig, defineConfig } from "@chakra-ui/react";

const v = (name: string) => `var(--${name})`;

const config = defineConfig({
  cssVarsPrefix: "sysg",
  preflight: true,
  globalCss: {
    "html, body": {
      margin: 0,
      padding: 0,
      background: v("surface-page"),
      color: v("text-body"),
      fontFamily: v("font-body"),
      fontSize: v("fs-body"),
      lineHeight: v("lh-body"),
    },
    body: { minHeight: "100vh", textWrap: "pretty", display: "flex", flexDirection: "column" },
    "h1, h2, h3, h4": { textWrap: "balance", fontFamily: v("font-heading"), color: v("text-heading") },
    "code, kbd, pre, samp": { fontFamily: v("font-mono"), fontVariantLigatures: "none" },
    a: { color: v("text-link"), textDecoration: "none" },
    "a:hover": { color: v("text-link-hover") },
    "*:focus-visible": { outline: `2px solid ${v("border-focus")}`, outlineOffset: "2px" },
  },
  theme: {
    breakpoints: {
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    tokens: {
      fonts: {
        body: { value: v("font-body") },
        heading: { value: v("font-heading") },
        display: { value: v("font-display") },
        mono: { value: v("font-mono") },
      },
      fontWeights: {
        regular: { value: v("fw-regular") },
        medium: { value: v("fw-medium") },
        semibold: { value: v("fw-semibold") },
        bold: { value: v("fw-bold") },
      },
      fontSizes: {
        hero: { value: v("fs-hero") },
        h1: { value: v("fs-h1") },
        cardTitle: { value: v("fs-card-title") },
        h2: { value: v("fs-h2") },
        h3: { value: v("fs-h3") },
        lead: { value: v("fs-lead") },
        bodyLg: { value: v("fs-body-lg") },
        body: { value: v("fs-body") },
        bodySm: { value: v("fs-body-sm") },
        meta: { value: v("fs-meta") },
        micro: { value: v("fs-micro") },
      },
      colors: {
        paper: {
          1: { value: v("paper-1") },
          2: { value: v("paper-2") },
          3: { value: v("paper-3") },
          4: { value: v("paper-4") },
          5: { value: v("paper-5") },
          hover: { value: v("paper-hover") },
        },
        line: {
          1: { value: v("line-1") },
          2: { value: v("line-2") },
          3: { value: v("line-3") },
          4: { value: v("line-4") },
          dim: { value: v("glyph-dim") },
        },
        ink: {
          1: { value: v("ink-1") },
          2: { value: v("ink-2") },
          3: { value: v("ink-3") },
          4: { value: v("ink-4") },
          5: { value: v("ink-5") },
          6: { value: v("ink-6") },
        },
        accent: {
          300: { value: v("accent-300") },
          500: { value: v("accent-500") },
          600: { value: v("accent-600") },
          700: { value: v("accent-700") },
          tint: { value: v("accent-tint") },
        },
        warn: {
          300: { value: v("warn-300") },
          500: { value: v("warn-500") },
          tint: { value: v("warn-tint") },
        },
        channel: {
          blue: { value: v("channel-blue") },
          violet: { value: v("channel-violet") },
          neutral: { value: v("bar-neutral") },
        },
      },
      radii: {
        none: { value: v("radius-0") },
        xs: { value: v("radius-xs") },
        sm: { value: v("radius-sm") },
        md: { value: v("radius-md") },
        lg: { value: v("radius-lg") },
        pill: { value: v("radius-pill") },
      },
      shadows: {
        none: { value: "none" },
        card: { value: v("shadow-card") },
      },
      durations: {
        instant: { value: v("dur-instant") },
        fast: { value: v("dur-fast") },
        base: { value: v("dur-base") },
        cross: { value: v("dur-cross") },
        slow: { value: v("dur-slow") },
      },
      easings: {
        out: { value: v("ease-out") },
        inOut: { value: v("ease-in-out") },
        linear: { value: "linear" },
      },
      sizes: {
        nav: { value: v("layout-nav-h") },
        sidebar: { value: v("layout-sidebar-w") },
        toc: { value: v("layout-toc-w") },
        content: { value: v("layout-content-max") },
        page: { value: v("layout-page-max") },
      },
      spacing: {
        gutter: { value: v("layout-gutter") },
        block: { value: v("stack-block") },
        section: { value: v("stack-section") },
        tight: { value: v("stack-tight") },
        card: { value: v("pad-card") },
      },
    },
    semanticTokens: {
      colors: {
        text: {
          heading: { value: v("text-heading") },
          body: { value: v("text-body") },
          secondary: { value: v("text-secondary") },
          muted: { value: v("text-muted") },
          faint: { value: v("text-faint") },
          footer: { value: v("text-footer") },
          link: { value: v("text-link") },
          linkHover: { value: v("text-link-hover") },
          inverse: { value: v("text-inverse") },
          accent: { value: v("text-accent") },
          code: { value: v("text-code") },
        },
        surface: {
          page: { value: v("surface-page") },
          card: { value: v("surface-card") },
          subtle: { value: v("surface-subtle") },
          sunken: { value: v("surface-sunken") },
          inlineCode: { value: v("surface-inline-code") },
          track: { value: v("surface-track") },
          code: { value: v("surface-code") },
          codeHeader: { value: v("surface-code-header") },
          terminal: { value: v("surface-terminal") },
          nav: { value: v("surface-nav") },
        },
        border: {
          default: { value: v("border-default") },
          rule: { value: v("border-rule") },
          strong: { value: v("border-strong") },
          control: { value: v("border-control") },
          controlHover: { value: v("border-control-hover") },
          code: { value: v("border-code") },
          focus: { value: v("border-focus") },
        },
        action: {
          primary: { value: v("action-primary") },
          primaryHover: { value: v("action-primary-hover") },
          ghostHover: { value: v("action-ghost-hover") },
        },
        status: {
          okFg: { value: v("status-ok-fg") },
          okBg: { value: v("status-ok-bg") },
          warnFg: { value: v("status-warn-fg") },
          warnBg: { value: v("status-warn-bg") },
          infoFg: { value: v("status-info-fg") },
          infoBg: { value: v("status-info-bg") },
          neutralFg: { value: v("status-neutral-fg") },
          neutralBg: { value: v("status-neutral-bg") },
        },
        code: {
          text: { value: v("code-text") },
          comment: { value: v("code-comment") },
          key: { value: v("code-key") },
          string: { value: v("code-string") },
          number: { value: v("code-number") },
          flag: { value: v("code-flag") },
          punct: { value: v("code-punct") },
          caret: { value: v("code-caret") },
        },
        callout: {
          infoBg: { value: v("callout-info-bg") },
          infoRule: { value: v("callout-info-rule") },
          noteBg: { value: v("callout-note-bg") },
          noteRule: { value: v("callout-note-rule") },
          warningBg: { value: v("callout-warning-bg") },
          warningRule: { value: v("callout-warning-rule") },
        },
      },
    },
  },
});

export const system = createSystem(defaultBaseConfig, config);
