FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main

ARG RUST_VERSION=1.90.0

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    binutils-aarch64-linux-gnu \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    gcc \
    git \
    libclang-dev \
    libssl-dev \
    lld \
    llvm \
    pkg-config \
    tzdata \
    wget \
    && apt-get clean
