//! Boot integration: the service-manager unit that starts a manifest at boot.
//!
//! A supervisor is only supervised if the process the service manager tracks
//! *is* the supervisor, so every unit rendered here runs `start --attached`
//! (never `--daemonize`, which detaches and leaves the manager tracking a
//! process that has already exited). Teardown is a plain signal to that
//! process: sysg's own shutdown path then stops services in reverse dependency
//! order, which is why the manager is told to signal the main process only.

use std::{
    fmt,
    os::unix::ffi::OsStringExt,
    path::{Path, PathBuf},
};

use crate::{runtime, version::CLI_VERSION};

/// Marker written into every generated unit, so a later `install-boot` can tell
/// a unit it owns from one an operator hand-wrote at the same path.
pub const MARKER: &str = "Generated by sysg install-boot";

/// How long the manager waits for a graceful teardown before killing what is
/// left. Generous, because the supervisor stops each service in turn and each
/// one gets its own grace period.
const STOP_TIMEOUT_SECS: u32 = 90;

/// Delay before the manager restarts a supervisor that died.
const RESTART_DELAY_SECS: u32 = 5;

/// Window and burst that stop a supervisor which dies on a bad manifest from
/// being restarted forever.
const START_LIMIT_WINDOW_SECS: u32 = 60;
/// How many starts are allowed inside [`START_LIMIT_WINDOW_SECS`].
const START_LIMIT_BURST: u32 = 3;

/// Which service-manager scope a unit is installed into.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scope {
    /// The invoking user's own manager: `systemd --user`, or a LaunchAgent.
    User,
    /// The machine's manager: a systemd system unit, or a LaunchDaemon.
    System,
}

impl fmt::Display for Scope {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::User => "user",
            Self::System => "system",
        })
    }
}

/// The service manager a unit is written for, chosen by platform.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Manager {
    /// systemd, on Linux.
    Systemd,
    /// launchd, on macOS.
    Launchd,
}

impl Manager {
    /// The manager native to this platform.
    ///
    /// This says which manager a unit would be *written for*, not that the
    /// manager is running — a systemd unit rendered on a runit box is still a
    /// valid unit for the systemd host it gets copied to. Ask
    /// [`running_manager`] before putting one on disk.
    pub fn native() -> Self {
        if cfg!(target_os = "macos") {
            Self::Launchd
        } else {
            Self::Systemd
        }
    }
}

/// The manager actually running on this machine, if it is one sysg renders for.
///
/// `None` means the host boots something else — runit, s6, OpenRC, a bare
/// container entrypoint — and a unit written here would never be read.
pub fn running_manager() -> Option<Manager> {
    manager_under(Path::new("/"))
}

/// [`running_manager`], rooted at `root` so tests can stage a machine.
///
/// The Linux probe is the one `sd_booted(3)` uses: systemd creates
/// `/run/systemd/system` when it boots the machine, and nothing else does.
/// Checking for the `systemctl` binary would not do — a host can carry it as a
/// dependency of something else while running a different init entirely.
///
/// `root` reaches only that probe. macOS answers launchd from the target alone,
/// since nothing else has ever been PID 1 there, so staging a root directory
/// cannot make a macOS build say anything else.
fn manager_under(root: &Path) -> Option<Manager> {
    if cfg!(target_os = "macos") {
        return Some(Manager::Launchd);
    }
    root.join("run/systemd/system")
        .is_dir()
        .then_some(Manager::Systemd)
}

/// What PID 1 calls itself, for an error message that can name the init the
/// operator is looking at.
///
/// Advisory only, and never a verdict: `/proc/1/comm` is a process name, so it
/// can read `systemd` on a container where systemd never booted the machine and
/// the run-directory probe rightly says no. Unreadable under some container
/// configurations, and absent entirely off Linux.
pub fn init_name() -> Option<String> {
    plain_init_name(&std::fs::read_to_string("/proc/1/comm").ok()?)
}

/// Accepts `/proc/1/comm` only when it is a short, plain word.
///
/// The contents are whatever PID 1 was named, and this ends up inside a
/// diagnostic; anything else is dropped rather than printed.
fn plain_init_name(raw: &str) -> Option<String> {
    let name = raw.trim();
    let plain = !name.is_empty()
        && name.len() <= 32
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'));
    plain.then(|| name.to_string())
}

/// Everything a rendered unit needs to boot one manifest.
#[derive(Debug, Clone)]
pub struct Unit {
    /// Unit name without extension (`sysg`, `sysg-prod`).
    pub name: String,
    /// Absolute path of the sysg binary the unit invokes.
    pub exe: PathBuf,
    /// Absolute path of the manifest to boot.
    pub config: PathBuf,
    /// Directory the supervisor runs from; relative commands in the manifest
    /// resolve against it.
    pub workdir: PathBuf,
    /// Which manager scope this unit installs into.
    pub scope: Scope,
    /// Whether the unit targets the system runtime (`--sys`).
    pub sys: bool,
    /// Account the manager runs the supervisor as. System scope only; user
    /// scope already runs as the invoking user.
    pub account: Option<String>,
    /// Home directory for `account`, without which the user runtime would
    /// resolve its state under `/`.
    pub home: Option<PathBuf>,
    /// Where launchd writes the supervisor's own stdout/stderr.
    pub log_dir: PathBuf,
    /// The manager to render for.
    pub manager: Manager,
    /// Order the supervisor after the network is actually configured, not just
    /// after the network stack has been brought up.
    pub wait_online: bool,
}

impl Unit {
    /// Builds a unit for `config` with defaults taken from the running binary
    /// and the active runtime.
    pub fn new(config: PathBuf, scope: Scope) -> Result<Self, Error> {
        if !config.is_absolute() {
            return Err(Error::RelativePath("config", config));
        }
        let exe = running_exe()?;
        let workdir = config
            .parent()
            .map(Path::to_path_buf)
            .unwrap_or_else(|| PathBuf::from("/"));

        Ok(Self {
            name: default_name(&config),
            exe,
            config,
            workdir,
            scope,
            sys: runtime::mode() == runtime::RuntimeMode::System,
            account: None,
            home: None,
            log_dir: runtime::log_dir(),
            manager: Manager::native(),
            wait_online: false,
        })
    }

    /// Rejects combinations that would render a unit that cannot work.
    pub fn check(&self) -> Result<(), Error> {
        if self.sys && self.scope == Scope::User {
            return Err(Error::SysUnderUserScope);
        }
        if self.account.is_some() && self.scope == Scope::User {
            return Err(Error::AccountUnderUserScope);
        }
        if self.sys && self.account.is_some() {
            return Err(Error::AccountUnderSys);
        }
        if self.scope == Scope::System && !self.sys && self.account.is_none() {
            return Err(Error::SystemScopeNeedsOwner);
        }
        if !self.workdir.is_absolute() {
            return Err(Error::RelativePath("workdir", self.workdir.clone()));
        }
        if !self.exe.is_absolute() {
            return Err(Error::RelativePath("exe", self.exe.clone()));
        }
        if !is_executable_file(&self.exe) {
            return Err(Error::ExeMissing(self.exe.clone()));
        }
        let mut values = vec![
            ("config", self.config.as_path()),
            ("workdir", self.workdir.as_path()),
            ("exe", self.exe.as_path()),
            ("log dir", self.log_dir.as_path()),
        ];
        if let Some(home) = &self.home {
            values.push(("home", home.as_path()));
        }
        for (what, path) in values {
            let text = path.to_str().ok_or(Error::NotUtf8(what))?;
            if breaks_the_line(text) {
                return Err(Error::LineBreak(what));
            }
        }
        if let Some(account) = &self.account
            && breaks_the_line(account)
        {
            return Err(Error::LineBreak("account"));
        }
        if self.wait_online && self.manager == Manager::Launchd {
            return Err(Error::Unsupported("--wait-online", self.manager));
        }
        check_name(&self.name)
    }

    /// Refuses a unit whose manager is not the one running this machine.
    ///
    /// Rendering stays host-neutral — a unit generated on a build box is the
    /// right unit for the host it is copied to — so this is asked only before
    /// the unit goes on disk, never in [`Unit::check`].
    pub fn writable_here(&self, running: Option<Manager>) -> Result<(), Error> {
        if running == Some(self.manager) {
            return Ok(());
        }
        Err(Error::NoSupportedManager(init_name()))
    }

    /// Where the rendered unit is installed.
    pub fn path(&self, home: Option<&Path>) -> Result<PathBuf, Error> {
        let dir = match self.scope {
            Scope::System => system_install_dir(self.manager),
            Scope::User => {
                user_install_dir(self.manager, home.ok_or(Error::HomeUnknown)?)
            }
        };
        Ok(match self.manager {
            Manager::Systemd => dir.join(format!("{}.service", self.name)),
            Manager::Launchd => dir.join(self.plist_label() + ".plist"),
        })
    }

    /// The reverse-DNS label launchd knows this daemon by.
    pub fn plist_label(&self) -> String {
        format!("dev.sysg.{}", self.name)
    }

    /// The argv the manager runs.
    pub fn argv(&self) -> Vec<String> {
        let mut argv = vec![self.exe.to_string_lossy().into_owned()];
        if self.sys {
            argv.push("--sys".into());
        }
        argv.push("start".into());
        argv.push("--attached".into());
        argv.push("--config".into());
        argv.push(self.config.to_string_lossy().into_owned());
        argv
    }

    /// The runtime directory this unit's supervisor will use.
    pub fn runtime_dir(&self, caller_home: Option<&Path>) -> Option<PathBuf> {
        if self.sys {
            return Some(runtime::system_state_dir());
        }
        let home = self
            .home
            .clone()
            .or_else(|| caller_home.map(Path::to_path_buf))?;
        Some(state_dir_for_home(&home))
    }

    /// Renders the unit for its manager.
    pub fn render(&self) -> String {
        match self.manager {
            Manager::Systemd => self.render_systemd(),
            Manager::Launchd => self.render_launchd(),
        }
    }

    /// The commands that activate a written unit, in order.
    pub fn enable_steps(&self, path: &Path) -> Vec<Step> {
        let argv = |parts: &[&str]| -> Vec<String> {
            parts.iter().map(|part| (*part).to_string()).collect()
        };
        match (self.manager, self.scope) {
            (Manager::Systemd, Scope::System) => vec![
                Step::required(argv(&["systemctl", "daemon-reload"])),
                Step::required(argv(&[
                    "systemctl",
                    "enable",
                    "--now",
                    &format!("{}.service", self.name),
                ])),
            ],
            (Manager::Systemd, Scope::User) => vec![
                Step::required(argv(&["systemctl", "--user", "daemon-reload"])),
                Step::required(argv(&[
                    "systemctl",
                    "--user",
                    "enable",
                    "--now",
                    &format!("{}.service", self.name),
                ])),
                Step::required(argv(&[
                    "loginctl",
                    "enable-linger",
                    &whoami().unwrap_or_else(|| "$USER".into()),
                ])),
            ],
            (Manager::Launchd, scope) => {
                let domain = match scope {
                    Scope::System => "system".to_string(),
                    Scope::User => format!("gui/{}", nix::unistd::Uid::current()),
                };
                vec![
                    Step::optional(argv(&[
                        "launchctl",
                        "bootout",
                        &format!("{domain}/{}", self.plist_label()),
                    ])),
                    Step::required(argv(&[
                        "launchctl",
                        "bootstrap",
                        &domain,
                        &path.to_string_lossy(),
                    ])),
                ]
            }
        }
    }

    /// Whether a unit already at `path` was written by sysg, and so may be
    /// replaced without destroying an operator's own work.
    pub fn owns(path: &Path) -> bool {
        std::fs::read_to_string(path).is_ok_and(|existing| existing.contains(MARKER))
    }

    /// Renders a systemd unit.
    fn render_systemd(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!("# {MARKER} (sysg {CLI_VERSION})\n"));
        out.push_str("[Unit]\n");
        out.push_str(&format!(
            "Description=Systemg supervisor ({})\n",
            systemd_value(&self.name)
        ));
        if self.wait_online {
            out.push_str("Wants=network-online.target\n");
            out.push_str("After=network-online.target\n");
        } else {
            out.push_str("After=network.target\n");
        }
        out.push_str(&format!(
            "StartLimitIntervalSec={START_LIMIT_WINDOW_SECS}\n"
        ));
        out.push_str(&format!("StartLimitBurst={START_LIMIT_BURST}\n\n"));

        out.push_str("[Service]\n");
        out.push_str("Type=simple\n");
        let argv: Vec<String> = self
            .argv()
            .iter()
            .map(|arg| systemd_exec_arg(arg))
            .collect();
        out.push_str(&format!("ExecStart={}\n", argv.join(" ")));
        out.push_str(&format!(
            "WorkingDirectory={}\n",
            systemd_arg(&self.workdir.to_string_lossy())
        ));
        if let Some(account) = &self.account {
            out.push_str(&format!("User={}\n", systemd_arg(account)));
        }
        if let Some(home) = &self.home {
            out.push_str(&format!(
                "Environment={}\n",
                systemd_arg(&format!("HOME={}", home.display()))
            ));
        }
        out.push_str("KillMode=mixed\n");
        out.push_str(&format!("TimeoutStopSec={STOP_TIMEOUT_SECS}\n"));
        out.push_str("Restart=on-failure\n");
        out.push_str(&format!("RestartSec={RESTART_DELAY_SECS}\n\n"));

        out.push_str("[Install]\n");
        out.push_str(match self.scope {
            Scope::System => "WantedBy=multi-user.target\n",
            Scope::User => "WantedBy=default.target\n",
        });
        out
    }

    /// Renders a launchd property list.
    fn render_launchd(&self) -> String {
        let label = self.plist_label();
        let mut args = String::new();
        for arg in self.argv() {
            args.push_str(&format!("    <string>{}</string>\n", xml_escape(&arg)));
        }
        let account = self.account.as_ref().map(|account| {
            format!(
                "  <key>UserName</key>\n  <string>{}</string>\n",
                xml_escape(account)
            )
        });
        let home = self.home.as_ref().map(|home| {
            format!(
                "  <key>EnvironmentVariables</key>\n  <dict>\n    <key>HOME</key>\n    <string>{}</string>\n  </dict>\n",
                xml_escape(&home.to_string_lossy())
            )
        });

        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- {marker} (sysg {version}) -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
{args}  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>{restart_delay}</integer>
  <key>ExitTimeOut</key>
  <integer>{stop_timeout}</integer>
  <key>WorkingDirectory</key>
  <string>{workdir}</string>
{account}{home}  <key>StandardOutPath</key>
  <string>{log_dir}/{name}.out.log</string>
  <key>StandardErrorPath</key>
  <string>{log_dir}/{name}.err.log</string>
</dict>
</plist>
"#,
            marker = MARKER,
            version = CLI_VERSION,
            restart_delay = RESTART_DELAY_SECS,
            stop_timeout = STOP_TIMEOUT_SECS,
            label = label,
            args = args,
            workdir = xml_escape(&self.workdir.to_string_lossy()),
            account = account.unwrap_or_default(),
            home = home.unwrap_or_default(),
            log_dir = xml_escape(&self.log_dir.to_string_lossy()),
            name = self.name,
        )
    }
}

/// One command that activates an installed unit.
#[derive(Debug, Clone)]
pub struct Step {
    /// The program and its arguments.
    pub argv: Vec<String>,
    /// Whether a non-zero exit ends the activation. `launchctl bootout` runs
    /// first to make `bootstrap` idempotent, and fails whenever the job was not
    /// already loaded — which is the ordinary case.
    pub required: bool,
}

impl Step {
    /// A step whose failure fails the activation.
    fn required(argv: Vec<String>) -> Self {
        Self {
            argv,
            required: true,
        }
    }

    /// A step that may fail without ending the activation.
    fn optional(argv: Vec<String>) -> Self {
        Self {
            argv,
            required: false,
        }
    }

    /// The step as one printable command line.
    pub fn line(&self) -> String {
        self.argv.join(" ")
    }
}

/// Why a unit could not be rendered or installed.
#[derive(Debug)]
pub enum Error {
    /// A path that must be absolute was not.
    RelativePath(&'static str, PathBuf),
    /// The running binary's own path is unknown, so no unit can name it.
    ExeUnknown,
    /// The running binary's path names nothing on disk — it was replaced or
    /// deleted while running, so a unit built from it would fail at boot.
    ExeMissing(PathBuf),
    /// `--name` was not a single ordinary filename component.
    NameInvalid(String),
    /// A directory could not be handed to the account the unit runs as.
    Chown(PathBuf, String),
    /// A value holds a line break, which would end its directive and turn the
    /// remainder into one of its own.
    LineBreak(&'static str),
    /// A supervisor this manager did not start is already resident, so the unit
    /// would lose the runtime race the moment it was activated.
    SupervisorResident,
    /// Another unit already boots this runtime, from a different manifest. One
    /// runtime holds one supervisor, so the second unit could only fail.
    RuntimeTaken(PathBuf),
    /// A value is not valid UTF-8, so it cannot be written into a unit without
    /// being altered.
    NotUtf8(&'static str),
    /// Another unit already boots this manifest under a different name.
    AlreadyInstalled(PathBuf),
    /// A path that must be a plain directory is a symlink or something else, so
    /// preparing it as root could hand away whatever it points at.
    UnsafeComponent(PathBuf),
    /// A flag was given that the platform's service manager has no equivalent
    /// for, so honouring it is impossible and ignoring it would be a lie.
    Unsupported(&'static str, Manager),
    /// A user-scope path was requested without a home directory.
    HomeUnknown,
    /// `--sys` cannot be supervised by a user manager, which never has root.
    SysUnderUserScope,
    /// A user-scope unit already runs as the invoking user.
    AccountUnderUserScope,
    /// The system runtime is root's; it cannot also run as another account.
    AccountUnderSys,
    /// A unit already exists at the target path and sysg did not write it.
    Foreign(PathBuf),
    /// `--run-as` named an account the passwd database does not know.
    AccountUnknown(String),
    /// An activation step the service manager ran came back non-zero.
    EnableFailed(String, Option<i32>),
    /// An activation step could not be run at all — its program is missing, or
    /// the spawn itself failed.
    EnableSpawnFailed(String, String),
    /// The manager this unit is written for is not the one running this
    /// machine, so the unit would never be read. Carries what PID 1 calls
    /// itself, when that could be read.
    NoSupportedManager(Option<String>),
    /// A system-scope unit named neither the system runtime nor an account, so
    /// it would run the user runtime as root.
    SystemScopeNeedsOwner,
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RelativePath(what, path) => {
                write!(f, "{what} must be an absolute path: {}", path.display())
            }
            Self::ExeUnknown => f.write_str("this binary's own path could not be resolved"),
            Self::ExeMissing(path) => write!(
                f,
                "{} no longer exists, so a unit naming it would fail at boot; pass --exe with the installed path",
                path.display()
            ),
            Self::HomeUnknown => f.write_str("no home directory is set"),
            Self::SysUnderUserScope => {
                f.write_str("--sys targets the root-owned system runtime, which a user manager cannot start")
            }
            Self::AccountUnderUserScope => {
                f.write_str("a user-scope unit already runs as the invoking user")
            }
            Self::AccountUnderSys => {
                f.write_str("the system runtime is owned by root and cannot run as another account")
            }
            Self::Foreign(path) => {
                write!(f, "{} was not written by sysg", path.display())
            }
            Self::AccountUnknown(account) => {
                write!(f, "no account named '{account}' exists on this machine")
            }
            Self::SystemScopeNeedsOwner => f.write_str(
                "a system-scope unit runs as root, so it must target the system runtime (--sys) or name an account (--run-as)",
            ),
            Self::NameInvalid(name) => write!(
                f,
                "'{name}' is not a usable unit name: letters, digits, '-', '_' and '.' only, at most 64 of them"
            ),
            Self::Chown(path, reason) => {
                write!(f, "{} could not be given to the account: {reason}", path.display())
            }
            Self::LineBreak(what) => {
                write!(f, "the {what} path contains a line break, which a unit file cannot carry")
            }
            Self::SupervisorResident => f.write_str(
                "a supervisor started outside the service manager is already running; the unit would start and immediately lose the runtime to it",
            ),
            Self::RuntimeTaken(config) => write!(
                f,
                "a service-managed supervisor already owns this runtime, booting {}",
                config.display()
            ),
            Self::AlreadyInstalled(path) => write!(
                f,
                "{} already boots this runtime",
                path.display()
            ),
            Self::UnsafeComponent(path) => write!(
                f,
                "{} is not a plain directory, so preparing it as root could hand away whatever it points at",
                path.display()
            ),
            Self::NotUtf8(what) => {
                write!(f, "the {what} path is not valid UTF-8, so no unit can name it exactly")
            }
            Self::Unsupported(flag, manager) => {
                write!(f, "{flag} has no equivalent under {manager:?}")
            }
            Self::EnableFailed(step, code) => match code {
                Some(code) => write!(f, "`{step}` exited {code}"),
                None => write!(f, "`{step}` was killed by a signal"),
            },
            Self::EnableSpawnFailed(step, reason) => {
                write!(f, "`{step}` could not be run: {reason}")
            }
            Self::NoSupportedManager(init) => match init {
                Some(init) => write!(
                    f,
                    "PID 1 is named `{init}`, and the manager this unit targets is not running here; sysg writes systemd units and launchd plists, nothing else"
                ),
                None => f.write_str(
                    "the manager this unit targets is not running here; sysg writes systemd units and launchd plists, nothing else",
                ),
            },
        }
    }
}

impl std::error::Error for Error {}

/// Accepts only unit names that are a single, ordinary filename component: a
/// name reaches a filesystem path, a systemd directive, and a plist label, and
/// any of `/`, `..`, or a newline in it would write somewhere else entirely.
pub fn check_name(name: &str) -> Result<(), Error> {
    let ordinary = !name.is_empty()
        && name.len() <= 64
        && name != ".."
        && !name.starts_with('-')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'));
    if ordinary {
        Ok(())
    } else {
        Err(Error::NameInvalid(name.to_string()))
    }
}

/// Derives a unit name from the manifest's filename.
fn default_name(config: &Path) -> String {
    let stem = config
        .file_stem()
        .map(|stem| stem.to_string_lossy().into_owned())
        .unwrap_or_default();
    let sanitized: String = stem
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let trimmed = sanitized.trim_matches('-');
    match trimmed {
        "" | "systemg" | "sysg" => "sysg".into(),
        other => other.to_lowercase(),
    }
}

/// This binary's own path, as a unit may name it.
///
/// Linux reports a replaced binary as `/proc/self/exe -> "<path> (deleted)"`,
/// and an upgrade replaces the binary in place — so the obvious
/// `current_exe()` can hand back a path that names nothing. A unit written from
/// it would fail at the next boot, long after whoever ran `install-boot` could
/// connect the two, so an unusable path is refused instead of written.
pub fn running_exe() -> Result<PathBuf, Error> {
    running_exe_from(std::env::current_exe().map_err(|_| Error::ExeUnknown)?)
}

/// The live path behind what the kernel reported as this binary's location.
fn running_exe_from(reported: PathBuf) -> Result<PathBuf, Error> {
    let exe = match reported.to_string_lossy().strip_suffix(" (deleted)") {
        Some(live) => PathBuf::from(live),
        None => reported,
    };
    if !is_executable_file(&exe) {
        return Err(Error::ExeMissing(exe));
    }
    Ok(exe)
}

/// Where `manager` keeps its system-scope units.
pub fn system_install_dir(manager: Manager) -> PathBuf {
    match manager {
        Manager::Systemd => PathBuf::from("/etc/systemd/system"),
        Manager::Launchd => PathBuf::from("/Library/LaunchDaemons"),
    }
}

/// Where `manager` keeps the user-scope units belonging to `home`.
pub fn user_install_dir(manager: Manager, home: &Path) -> PathBuf {
    match manager {
        Manager::Systemd => home.join(".config/systemd/user"),
        Manager::Launchd => home.join("Library/LaunchAgents"),
    }
}

/// The runtime state directory belonging to `home` — the runtime a unit running
/// as that account will target.
pub fn state_dir_for_home(home: &Path) -> PathBuf {
    home.join(".local/share/systemg")
}

/// The runtime log directory belonging to `home`, where a supervisor started
/// under another account writes its own output.
pub fn log_dir_for_home(home: &Path) -> PathBuf {
    state_dir_for_home(home).join("logs")
}

/// Whether `path` is a regular file this machine can actually execute. A
/// directory or a non-executable file at the unit's `ExecStart` is a unit that
/// fails at boot, so it is refused the same way a missing one is.
fn is_executable_file(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;

    std::fs::metadata(path)
        .is_ok_and(|meta| meta.is_file() && meta.permissions().mode() & 0o111 != 0)
}

/// Creates every missing component of `path` beneath `home` and hands each one
/// to `account`, including components that already exist but belong to someone
/// else. A supervisor that cannot write its own state directory fails at every
/// boot, and the manager reports only an exit code.
///
/// The tree lives inside an account's own home, so that account can swap any
/// part of it for a symlink between one syscall and the next. Every step is
/// therefore taken relative to an open directory descriptor with `O_NOFOLLOW`,
/// and ownership is changed with `fchown` on that descriptor: a component
/// replaced mid-walk fails the `openat` instead of redirecting root's `chown`
/// somewhere outside the home.
///
/// The directory the walk arrives at must belong to the account, which is the
/// backstop: however the path was spelled or linked, a walk that ended up
/// somewhere root owns is not that account's home, and nothing is created or
/// handed over there.
pub fn make_tree_for_account(
    path: &Path,
    home: &Path,
    account: &str,
) -> Result<(), Error> {
    let tail = path.strip_prefix(home).map_err(|_| {
        Error::Chown(
            path.to_path_buf(),
            format!("{} is not under {}", path.display(), home.display()),
        )
    })?;

    let (uid, gid) = account_ids(account)?;
    let mut parent = Dir::open_walking(home)?;
    if parent.owner(home)? != uid {
        return Err(Error::UnsafeComponent(home.to_path_buf()));
    }
    let mut walked = home.to_path_buf();

    for component in tail.components() {
        let std::path::Component::Normal(name) = component else {
            return Err(Error::UnsafeComponent(path.to_path_buf()));
        };
        walked.push(name);
        let raw = c_name(name, &walked)?;

        unsafe { libc::mkdirat(parent.0, raw.as_ptr(), 0o700) };
        let child = parent.open_child(&raw, &walked)?;
        if child.owner(&walked)? != uid {
            child.give_to(uid, gid, &walked)?;
        }
        parent = child;
    }
    Ok(())
}

/// An open directory descriptor, closed when it goes out of scope.
struct Dir(libc::c_int);

impl Dir {
    /// Opens `path` by walking it from the root one component at a time, so no
    /// component may be a symlink — not just the last. An account whose home
    /// sits below a directory it can write could otherwise point an
    /// intermediate component elsewhere and have root prepare a tree there.
    fn open_walking(path: &Path) -> Result<Self, Error> {
        Self::walk(path, 0)
    }

    /// Walks `path` from the root, one component at a time, never following a
    /// symlink blindly. A component that is a symlink is accepted only when
    /// root planted it in a directory nobody but root can change — a platform
    /// reaches its own trees that way, macOS through `/var` — and even then the
    /// link's target is walked under these same rules rather than opened
    /// outright, so an attacker-owned component *inside* that target cannot
    /// redirect what root does next.
    fn walk(path: &Path, depth: u32) -> Result<Self, Error> {
        let unsafe_path = || Error::UnsafeComponent(path.to_path_buf());
        if depth > Self::MAX_LINK_DEPTH {
            return Err(unsafe_path());
        }
        let mut components = path.components();
        if components.next() != Some(std::path::Component::RootDir) {
            return Err(unsafe_path());
        }

        let mut dir = Self::open(Path::new("/"))?;
        let mut walked = PathBuf::from("/");
        for component in components {
            let std::path::Component::Normal(name) = component else {
                return Err(unsafe_path());
            };
            walked.push(name);
            let raw = c_name(name, &walked)?;
            dir = match dir.open_child(&raw, &walked) {
                Ok(child) => child,
                Err(_) => {
                    let target = dir.read_root_link(&raw, &walked)?;
                    let target = if target.is_absolute() {
                        target
                    } else {
                        walked
                            .parent()
                            .map(|parent| parent.join(&target))
                            .ok_or_else(unsafe_path)?
                    };
                    let resolved = Self::walk(&target, depth + 1)?;
                    walked = target;
                    resolved
                }
            };
        }
        Ok(dir)
    }

    /// How many symlinks one walk may follow before giving up.
    const MAX_LINK_DEPTH: u32 = 8;

    /// Opens `path` itself, refusing to follow it if it is a symlink.
    fn open(path: &Path) -> Result<Self, Error> {
        let raw = std::ffi::CString::new(path.as_os_str().as_encoded_bytes()).map_err(
            |_| Error::Chown(path.to_path_buf(), "path contains a NUL byte".into()),
        )?;
        let fd = unsafe { libc::open(raw.as_ptr(), Self::FLAGS) };
        if fd < 0 {
            return Err(Error::UnsafeComponent(path.to_path_buf()));
        }
        Ok(Self(fd))
    }

    /// Opens a directory directly beneath this one, never through a symlink.
    fn open_child(&self, name: &std::ffi::CStr, walked: &Path) -> Result<Self, Error> {
        let fd = unsafe { libc::openat(self.0, name.as_ptr(), Self::FLAGS) };
        if fd < 0 {
            return Err(Error::UnsafeComponent(walked.to_path_buf()));
        }
        Ok(Self(fd))
    }

    /// Reads a component that is a symlink *root itself owns*, and refuses any
    /// other. A link an ordinary account could have planted is exactly the
    /// attack being closed here, so only root's own are read — and only from a
    /// directory nobody but root can change, since inspecting a name and using
    /// it are two separate calls.
    fn read_root_link(
        &self,
        name: &std::ffi::CStr,
        walked: &Path,
    ) -> Result<PathBuf, Error> {
        let refuse = || Error::UnsafeComponent(walked.to_path_buf());
        if !self.sealed() {
            return Err(refuse());
        }

        let mut stat = unsafe { std::mem::zeroed::<libc::stat>() };
        let described = unsafe {
            libc::fstatat(self.0, name.as_ptr(), &mut stat, libc::AT_SYMLINK_NOFOLLOW)
        };
        let planted_by_root = described == 0
            && stat.st_mode & libc::S_IFMT == libc::S_IFLNK
            && stat.st_uid == 0;
        if !planted_by_root {
            return Err(refuse());
        }

        let mut buffer = vec![0u8; libc::PATH_MAX as usize];
        let read = unsafe {
            libc::readlinkat(
                self.0,
                name.as_ptr(),
                buffer.as_mut_ptr().cast::<libc::c_char>(),
                buffer.len(),
            )
        };
        if read <= 0 || read as usize >= buffer.len() {
            return Err(refuse());
        }
        buffer.truncate(read as usize);
        Ok(PathBuf::from(std::ffi::OsString::from_vec(buffer)))
    }

    /// Whether only root can change what this directory contains. Inspecting a
    /// link and then opening it by name are two calls, so the link could be
    /// swapped in between — unless nobody but root can do the swapping.
    fn sealed(&self) -> bool {
        let mut stat = unsafe { std::mem::zeroed::<libc::stat>() };
        let described = unsafe { libc::fstat(self.0, &mut stat) } == 0;
        described
            && stat.st_uid == 0
            && stat.st_mode & (libc::S_IWGRP | libc::S_IWOTH) == 0
    }

    /// Who owns the directory this descriptor names.
    fn owner(&self, walked: &Path) -> Result<libc::uid_t, Error> {
        let mut stat = unsafe { std::mem::zeroed::<libc::stat>() };
        if unsafe { libc::fstat(self.0, &mut stat) } != 0 {
            return Err(Error::Chown(
                walked.to_path_buf(),
                std::io::Error::last_os_error().to_string(),
            ));
        }
        Ok(stat.st_uid)
    }

    /// Hands this directory to an account.
    fn give_to(
        &self,
        uid: libc::uid_t,
        gid: libc::gid_t,
        walked: &Path,
    ) -> Result<(), Error> {
        if unsafe { libc::fchown(self.0, uid, gid) } == 0 {
            Ok(())
        } else {
            Err(Error::Chown(
                walked.to_path_buf(),
                std::io::Error::last_os_error().to_string(),
            ))
        }
    }

    /// Open a real directory, never a symlink, and never inherited across exec.
    const FLAGS: libc::c_int =
        libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC;
}

impl Drop for Dir {
    fn drop(&mut self) {
        unsafe { libc::close(self.0) };
    }
}

/// One path component as a C string.
fn c_name(name: &std::ffi::OsStr, walked: &Path) -> Result<std::ffi::CString, Error> {
    std::ffi::CString::new(name.as_encoded_bytes())
        .map_err(|_| Error::UnsafeComponent(walked.to_path_buf()))
}

/// The uid and gid the passwd database records for `account`.
fn account_ids(account: &str) -> Result<(libc::uid_t, libc::gid_t), Error> {
    nix::unistd::User::from_name(account)
        .ok()
        .flatten()
        .map(|user| (user.uid.as_raw(), user.gid.as_raw()))
        .ok_or_else(|| Error::AccountUnknown(account.to_string()))
}

/// The home directory the passwd database records for `account`, so a system
/// unit running as another user does not resolve its state under `/`.
pub fn account_home(account: &str) -> Option<PathBuf> {
    nix::unistd::User::from_name(account)
        .ok()
        .flatten()
        .map(|user| user.dir)
}

/// The invoking account's name, for the lingering hint.
fn whoami() -> Option<String> {
    std::env::var("USER").ok().filter(|user| !user.is_empty())
}

/// Renders one systemd directive value: `%` is systemd's specifier prefix and
/// must be doubled, and a value carrying whitespace or a quote has to be quoted
/// or systemd reads it as several arguments.
fn systemd_arg(raw: &str) -> String {
    let escaped = systemd_value(raw);
    if escaped.is_empty()
        || escaped
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '\\' | '$' | ';'))
    {
        let quoted: String = escaped
            .chars()
            .flat_map(|c| {
                let escape = matches!(c, '"' | '\\');
                escape.then_some('\\').into_iter().chain(std::iter::once(c))
            })
            .collect();
        format!("\"{quoted}\"")
    } else {
        escaped
    }
}

/// Renders one argument of an `Exec*` line, where systemd additionally expands
/// `$VAR` and `${VAR}`: a literal dollar has to be doubled, and quoting alone
/// does not stop the expansion.
fn systemd_exec_arg(raw: &str) -> String {
    systemd_arg(&raw.replace('$', "$$"))
}

/// Doubles systemd's `%` specifier prefix, which is the one character every
/// directive expands.
fn systemd_value(raw: &str) -> String {
    raw.replace('%', "%%")
}

/// Whether a value would end its directive early and turn the rest into a
/// directive of its own. Such a value is refused rather than silently rewritten
/// — a path containing a newline is legal on Unix, so mangling it would write a
/// unit that boots the wrong thing.
fn breaks_the_line(raw: &str) -> bool {
    raw.contains(['\n', '\r'])
}

/// The runtime directory a rendered unit's supervisor will use, which is what
/// actually decides whether two units collide: a runtime holds exactly one
/// supervisor. Identity is the directory, not the account name — two names
/// sharing a home are one runtime, and `--run-as me` collides with my own
/// user-scope unit even though one names an account and the other does not.
///
/// `caller_home` stands in for a unit that names no account, which is the home
/// of whoever the manager will run it as.
pub fn runtime_dir_in_unit(text: &str, caller_home: Option<&Path>) -> Option<PathBuf> {
    if !text.contains(MARKER) {
        return None;
    }
    if unit_args(text).iter().any(|arg| arg == "--sys") {
        return Some(runtime::system_state_dir());
    }
    let home = home_in_unit(text)
        .or_else(|| account_in_unit(text).and_then(|account| account_home(&account)))
        .or_else(|| caller_home.map(Path::to_path_buf))?;
    Some(state_dir_for_home(&home))
}

/// The `HOME` a rendered unit sets for its supervisor, when it sets one.
fn home_in_unit(text: &str) -> Option<PathBuf> {
    if let Some(home) = text
        .lines()
        .find_map(|line| line.strip_prefix("Environment="))
        .map(unquote_systemd_value)
        .and_then(|value| value.strip_prefix("HOME=").map(str::to_string))
    {
        return Some(PathBuf::from(home));
    }
    text.split_once("<key>HOME</key>")
        .and_then(|(_, rest)| rest.split_once("<string>"))
        .and_then(|(_, rest)| rest.split_once("</string>"))
        .map(|(value, _)| PathBuf::from(xml_unescape(value)))
}

/// The account a rendered unit runs its supervisor as, when it names one.
fn account_in_unit(text: &str) -> Option<String> {
    if let Some(account) = text
        .lines()
        .find_map(|line| line.strip_prefix("User="))
        .map(unquote_systemd_value)
    {
        return Some(account);
    }
    text.split_once("<key>UserName</key>")
        .and_then(|(_, rest)| rest.split_once("<string>"))
        .and_then(|(_, rest)| rest.split_once("</string>"))
        .map(|(value, _)| xml_unescape(value))
}

/// Every argument a rendered unit carries, whichever manager wrote it.
fn unit_args(text: &str) -> Vec<String> {
    match text.lines().find(|line| line.starts_with("ExecStart=")) {
        Some(line) => split_systemd_args(line.trim_start_matches("ExecStart="), true),
        None => text
            .split("<string>")
            .skip(1)
            .filter_map(|chunk| chunk.split_once("</string>"))
            .map(|(value, _)| xml_unescape(value))
            .collect(),
    }
}

/// The manifest a rendered unit boots, read back out of the unit itself. Used
/// to spot a second unit that would boot the same manifest under another name —
/// two managers starting one manifest is two supervisors racing for one
/// runtime, which restart-loops forever.
pub fn config_in_unit(text: &str) -> Option<PathBuf> {
    if !text.contains(MARKER) {
        return None;
    }
    after_config_flag(unit_args(text).iter().map(String::as_str))
}

/// The value following a `--config` flag in a rendered argument list.
fn after_config_flag<'a>(args: impl Iterator<Item = &'a str>) -> Option<PathBuf> {
    let mut args = args.skip_while(|arg| *arg != "--config");
    args.next()?;
    args.next().map(PathBuf::from)
}

/// Splits a rendered `Exec*` line back into arguments, undoing the quoting and
/// the `%%`/`$$` doubling this module applies.
fn split_systemd_args(line: &str, exec: bool) -> Vec<String> {
    let mut args = Vec::new();
    let mut current = String::new();
    let mut quoted = false;
    let mut started = false;
    let mut chars = line.chars().peekable();

    while let Some(c) = chars.next() {
        match c {
            '\\' if quoted => {
                if let Some(next) = chars.next() {
                    current.push(next);
                }
            }
            '"' => {
                quoted = !quoted;
                started = true;
            }
            c if c.is_whitespace() && !quoted => {
                if started || !current.is_empty() {
                    args.push(std::mem::take(&mut current));
                    started = false;
                }
            }
            c => {
                current.push(c);
                started = true;
            }
        }
    }
    if started || !current.is_empty() {
        args.push(current);
    }
    args.into_iter()
        .map(|arg| {
            let arg = arg.replace("%%", "%");
            if exec { arg.replace("$$", "$") } else { arg }
        })
        .collect()
}

/// Undoes the quoting and `%%` doubling of a single directive value, which —
/// unlike an `Exec*` argument — never had its dollars doubled.
fn unquote_systemd_value(raw: &str) -> String {
    split_systemd_args(raw, false).join(" ")
}

/// Reverses [`xml_escape`].
fn xml_unescape(raw: &str) -> String {
    raw.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

/// Escapes the five XML entities so a path can sit inside a plist string.
fn xml_escape(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unit(scope: Scope, manager: Manager) -> Unit {
        Unit {
            name: "sysg-prod".into(),
            exe: PathBuf::from("/usr/bin/sysg"),
            config: PathBuf::from("/opts/gamecast/sysg.prod.yaml"),
            workdir: PathBuf::from("/opts/gamecast"),
            scope,
            sys: false,
            account: None,
            home: None,
            log_dir: PathBuf::from("/home/ubuntu/.local/share/systemg/logs"),
            manager,
            wait_online: false,
        }
    }

    #[test]
    fn every_unit_starts_attached_and_never_daemonizes() {
        for scope in [Scope::User, Scope::System] {
            for manager in [Manager::Systemd, Manager::Launchd] {
                let rendered = unit(scope, manager).render();
                assert!(rendered.contains("--attached"), "{scope} {manager:?}");
                assert!(!rendered.contains("--daemonize"), "{scope} {manager:?}");
                assert!(rendered.contains(MARKER), "{scope} {manager:?}");
            }
        }
    }

    #[test]
    fn systemd_system_unit_names_its_account_and_home() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.account = Some("ubuntu".into());
        unit.home = Some(PathBuf::from("/home/ubuntu"));
        let rendered = unit.render();

        assert!(rendered.contains("Type=simple"));
        assert!(rendered.contains(
            "ExecStart=/usr/bin/sysg start --attached --config /opts/gamecast/sysg.prod.yaml"
        ));
        assert!(rendered.contains("WorkingDirectory=/opts/gamecast"));
        assert!(rendered.contains("User=ubuntu"));
        assert!(rendered.contains("Environment=HOME=/home/ubuntu"));
        assert!(rendered.contains("KillMode=mixed"));
        assert!(rendered.contains("Restart=on-failure"));
        assert!(rendered.contains("WantedBy=multi-user.target"));
        assert!(!rendered.contains("ExecStop="));
    }

    #[test]
    fn system_runtime_unit_forwards_sys_to_every_invocation() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.sys = true;
        let rendered = unit.render();

        assert!(rendered.contains("ExecStart=/usr/bin/sysg --sys start --attached"));
        assert!(!rendered.contains("User="));
    }

    #[test]
    fn user_unit_installs_under_the_home_and_wants_the_default_target() {
        let unit = unit(Scope::User, Manager::Systemd);
        let home = PathBuf::from("/home/ubuntu");

        assert_eq!(
            unit.path(Some(&home)).expect("path"),
            home.join(".config/systemd/user/sysg-prod.service")
        );
        assert!(unit.render().contains("WantedBy=default.target"));
        assert!(
            unit.enable_steps(&home)
                .iter()
                .any(|step| step.argv.first().is_some_and(|arg| arg == "loginctl"))
        );
    }

    #[test]
    fn wait_online_orders_after_a_configured_network() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.sys = true;
        unit.wait_online = true;
        let rendered = unit.render();

        assert!(rendered.contains("Wants=network-online.target"));
        assert!(rendered.contains("After=network-online.target"));
    }

    #[test]
    fn launchd_restarts_only_a_supervisor_that_failed() {
        let rendered = unit(Scope::System, Manager::Launchd).render();

        assert!(rendered.contains("<key>SuccessfulExit</key>\n    <false/>"));
        assert!(rendered.contains("<key>RunAtLoad</key>"));
        assert!(rendered.contains("<key>ExitTimeOut</key>"));
        assert!(rendered.contains("<string>dev.sysg.sysg-prod</string>"));
    }

    #[test]
    fn launchd_escapes_paths_into_its_plist() {
        let mut unit = unit(Scope::User, Manager::Launchd);
        unit.config = PathBuf::from("/opts/a&b/sysg.yaml");
        assert!(unit.render().contains("/opts/a&amp;b/sysg.yaml"));
    }

    #[test]
    fn a_user_manager_cannot_own_the_system_runtime() {
        let mut unit = unit(Scope::User, Manager::Systemd);
        unit.sys = true;
        assert!(matches!(unit.check(), Err(Error::SysUnderUserScope)));
    }

    #[test]
    fn a_user_unit_cannot_name_another_account() {
        let mut unit = unit(Scope::User, Manager::Systemd);
        unit.account = Some("ubuntu".into());
        assert!(matches!(unit.check(), Err(Error::AccountUnderUserScope)));
    }

    #[test]
    fn a_system_unit_must_say_whose_runtime_it_boots() {
        let unit = unit(Scope::System, Manager::Systemd);
        assert!(matches!(unit.check(), Err(Error::SystemScopeNeedsOwner)));
    }

    #[test]
    fn a_relative_config_is_refused_before_anything_is_rendered() {
        assert!(matches!(
            Unit::new(PathBuf::from("systemg.yaml"), Scope::User),
            Err(Error::RelativePath("config", _))
        ));
    }

    #[test]
    #[cfg(target_os = "linux")]
    fn a_linux_host_counts_as_systemd_only_once_systemd_has_booted_it() {
        let root = tempfile::tempdir().expect("tempdir");
        assert_eq!(manager_under(root.path()), None);
        std::fs::create_dir_all(root.path().join("run/systemd/system")).expect("run dir");
        assert_eq!(manager_under(root.path()), Some(Manager::Systemd));
    }

    #[test]
    #[cfg(target_os = "macos")]
    fn macos_is_always_launchd() {
        let root = tempfile::tempdir().expect("tempdir");
        assert_eq!(manager_under(root.path()), Some(Manager::Launchd));
    }

    #[test]
    fn a_host_running_neither_manager_names_its_init_when_it_can() {
        let named = Error::NoSupportedManager(Some("runit".into())).to_string();
        assert!(named.contains("runit"), "{named}");
        let anonymous = Error::NoSupportedManager(None).to_string();
        assert!(anonymous.contains("systemd"), "{anonymous}");
        assert!(anonymous.contains("launchd"), "{anonymous}");
    }

    #[test]
    fn an_activation_step_that_could_not_run_says_so() {
        let err = Error::EnableSpawnFailed(
            "systemctl daemon-reload".into(),
            "No such file or directory (os error 2)".into(),
        );
        assert!(err.to_string().contains("could not be run"), "{err}");
    }

    #[test]
    fn only_a_short_plain_word_may_name_the_init() {
        assert_eq!(plain_init_name("runit\n"), Some("runit".into()));
        assert_eq!(plain_init_name("s6-svscan"), Some("s6-svscan".into()));
        assert_eq!(plain_init_name(""), None);
        assert_eq!(plain_init_name("   "), None);
        assert_eq!(plain_init_name("in it"), None);
        assert_eq!(plain_init_name("init\nNote: owned"), None);
        assert_eq!(plain_init_name("../../etc/passwd"), None);
        assert_eq!(plain_init_name(&"a".repeat(33)), None);
        assert_eq!(plain_init_name(&"a".repeat(32)), Some("a".repeat(32)));
    }

    #[test]
    fn a_unit_is_written_only_where_its_own_manager_runs() {
        let unit = unit(Scope::System, Manager::Systemd);
        assert!(unit.writable_here(Some(Manager::Systemd)).is_ok());
        assert!(matches!(
            unit.writable_here(Some(Manager::Launchd)),
            Err(Error::NoSupportedManager(_))
        ));
        assert!(matches!(
            unit.writable_here(None),
            Err(Error::NoSupportedManager(_))
        ));
    }

    #[test]
    fn unit_names_come_from_the_manifest_filename() {
        assert_eq!(
            default_name(Path::new("/opts/gamecast/sysg.prod.yaml")),
            "sysg-prod"
        );
        assert_eq!(default_name(Path::new("/etc/systemg/systemg.yaml")), "sysg");
        assert_eq!(default_name(Path::new("/srv/App Stack.yaml")), "app-stack");
    }

    #[test]
    fn exec_arguments_defuse_systemd_variable_expansion() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.sys = true;
        unit.config = PathBuf::from("/opt/$HOME/sysg.yaml");
        let rendered = unit.render();

        assert!(rendered.contains("/opt/$$HOME/sysg.yaml"), "{rendered}");
    }

    #[test]
    fn a_path_that_would_break_the_line_is_refused() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.sys = true;
        unit.exe = std::env::current_exe().expect("current exe");
        unit.workdir = PathBuf::from("/opt/one\nExecStart=/bin/sh");
        assert!(matches!(unit.check(), Err(Error::LineBreak("workdir"))));
    }

    #[test]
    fn a_tree_built_for_an_account_hands_over_every_directory_it_creates() {
        let home = tempfile::tempdir().expect("tempdir");
        let logs = home.path().join(".local/share/systemg/logs");
        let account = whoami().unwrap_or_else(|| "root".into());

        make_tree_for_account(&logs, home.path(), &account).expect("tree");
        assert!(logs.is_dir());
        assert!(home.path().join(".local").is_dir());
        assert!(home.path().join(".local/share/systemg").is_dir());
    }

    #[test]
    fn a_rendered_unit_gives_its_runtime_directory_back() {
        let mut sys = unit(Scope::System, Manager::Systemd);
        sys.sys = true;
        assert_eq!(
            runtime_dir_in_unit(&sys.render(), None),
            Some(runtime::system_state_dir())
        );

        let mut account = unit(Scope::System, Manager::Systemd);
        account.account = Some("app".into());
        account.home = Some(PathBuf::from("/home/app"));
        assert_eq!(
            runtime_dir_in_unit(&account.render(), None),
            Some(state_dir_for_home(Path::new("/home/app")))
        );

        let mut plist = unit(Scope::System, Manager::Launchd);
        plist.account = Some("app".into());
        plist.home = Some(PathBuf::from("/home/app"));
        assert_eq!(
            runtime_dir_in_unit(&plist.render(), None),
            Some(state_dir_for_home(Path::new("/home/app")))
        );

        let caller = unit(Scope::User, Manager::Systemd);
        assert_eq!(
            runtime_dir_in_unit(&caller.render(), Some(Path::new("/home/me"))),
            Some(state_dir_for_home(Path::new("/home/me")))
        );

        assert_eq!(
            runtime_dir_in_unit("[Service]\nExecStart=/usr/bin/true\n", None),
            None
        );
    }

    #[test]
    fn a_home_holding_a_specifier_survives_the_round_trip() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.account = Some("app".into());
        unit.home = Some(PathBuf::from("/home/100%app"));
        let rendered = unit.render();

        assert!(
            rendered.contains("Environment=HOME=/home/100%%app"),
            "{rendered}"
        );
        assert_eq!(
            runtime_dir_in_unit(&rendered, None),
            Some(state_dir_for_home(Path::new("/home/100%app")))
        );
    }

    #[test]
    fn a_home_with_a_space_survives_the_round_trip() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.account = Some("app".into());
        unit.home = Some(PathBuf::from("/home/my app"));
        let rendered = unit.render();

        assert_eq!(
            runtime_dir_in_unit(&rendered, None),
            Some(state_dir_for_home(Path::new("/home/my app")))
        );
    }

    #[test]
    fn a_home_the_account_does_not_own_is_refused() {
        let home = tempfile::tempdir().expect("tempdir");
        let home = std::fs::canonicalize(home.path()).expect("canonical");

        assert!(matches!(
            make_tree_for_account(&home.join(".local"), &home, "nobody"),
            Err(Error::UnsafeComponent(_))
        ));
    }

    #[test]
    fn a_symlinked_ancestor_of_the_home_is_refused_too() {
        let root = tempfile::tempdir().expect("tempdir");
        std::fs::create_dir_all(root.path().join("real")).expect("seed");
        std::os::unix::fs::symlink(root.path().join("real"), root.path().join("link"))
            .expect("symlink");
        let home = root.path().join("link/home");
        std::fs::create_dir_all(&home).expect("home");
        let account = whoami().unwrap_or_else(|| "root".into());

        assert!(matches!(
            make_tree_for_account(&home.join(".local"), &home, &account),
            Err(Error::UnsafeComponent(_))
        ));
    }

    #[test]
    fn a_user_unit_and_a_run_as_unit_for_one_home_are_one_runtime() {
        let mut mine = unit(Scope::User, Manager::Systemd);
        mine.home = None;
        let mut theirs = unit(Scope::System, Manager::Systemd);
        theirs.account = Some("me".into());
        theirs.home = Some(PathBuf::from("/home/me"));

        assert_eq!(
            mine.runtime_dir(Some(Path::new("/home/me"))),
            theirs.runtime_dir(None)
        );
    }

    #[test]
    fn two_accounts_with_their_own_homes_are_two_runtimes() {
        let mut first = unit(Scope::System, Manager::Systemd);
        first.account = Some("app".into());
        first.home = Some(PathBuf::from("/home/app"));
        let mut second = first.clone();
        second.account = Some("other".into());
        second.home = Some(PathBuf::from("/home/other"));

        assert_ne!(first.runtime_dir(None), second.runtime_dir(None));
    }

    #[test]
    fn a_symlinked_component_is_never_handed_over() {
        let home = tempfile::tempdir().expect("tempdir");
        std::fs::create_dir_all(home.path().join(".local")).expect("seed");
        std::os::unix::fs::symlink("/etc", home.path().join(".local/share"))
            .expect("symlink");
        let account = whoami().unwrap_or_else(|| "root".into());

        assert!(matches!(
            make_tree_for_account(
                &home.path().join(".local/share/systemg/logs"),
                home.path(),
                &account
            ),
            Err(Error::UnsafeComponent(_))
        ));
    }

    #[test]
    fn a_rendered_unit_gives_its_manifest_back() {
        let mut systemd = unit(Scope::System, Manager::Systemd);
        systemd.sys = true;
        systemd.config = PathBuf::from("/opt/my app/100% sysg.yaml");
        assert_eq!(
            config_in_unit(&systemd.render()),
            Some(PathBuf::from("/opt/my app/100% sysg.yaml"))
        );

        let mut launchd = unit(Scope::System, Manager::Launchd);
        launchd.sys = true;
        launchd.config = PathBuf::from("/opt/a&b/sysg.yaml");
        assert_eq!(
            config_in_unit(&launchd.render()),
            Some(PathBuf::from("/opt/a&b/sysg.yaml"))
        );

        assert_eq!(config_in_unit("[Service]\nExecStart=/usr/bin/true\n"), None);
    }

    #[test]
    fn an_existing_root_owned_directory_is_handed_over_too() {
        let home = tempfile::tempdir().expect("tempdir");
        let share = home.path().join(".local/share");
        std::fs::create_dir_all(&share).expect("seed");
        let account = whoami().unwrap_or_else(|| "root".into());

        make_tree_for_account(&share.join("systemg/logs"), home.path(), &account)
            .expect("tree");
        assert!(share.join("systemg/logs").is_dir());
    }

    #[test]
    fn a_path_outside_the_home_is_never_built_for_an_account() {
        let home = tempfile::tempdir().expect("tempdir");
        let elsewhere = PathBuf::from("/tmp/not-under-the-home");
        assert!(matches!(
            make_tree_for_account(&elsewhere, home.path(), "root"),
            Err(Error::Chown(..))
        ));
    }

    #[test]
    fn launchd_activation_boots_out_first_so_it_can_be_rerun() {
        let unit = unit(Scope::System, Manager::Launchd);
        let steps = unit.enable_steps(Path::new("/Library/LaunchDaemons/x.plist"));

        assert_eq!(steps.len(), 2);
        assert!(steps[0].line().starts_with("launchctl bootout"));
        assert!(!steps[0].required);
        assert!(steps[1].line().starts_with("launchctl bootstrap"));
        assert!(steps[1].required);
    }

    #[test]
    fn systemd_values_are_quoted_and_specifiers_doubled() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.config = PathBuf::from("/opt/my app/100% sysg.yaml");
        unit.workdir = PathBuf::from("/opt/my app");
        unit.account = Some("ubuntu".into());
        unit.home = Some(PathBuf::from("/home/my user"));
        let rendered = unit.render();

        assert!(
            rendered.contains(r#""/opt/my app/100%% sysg.yaml""#),
            "{rendered}"
        );
        assert!(
            rendered.contains(r#"WorkingDirectory="/opt/my app""#),
            "{rendered}"
        );
        assert!(
            rendered.contains(r#"Environment="HOME=/home/my user""#),
            "{rendered}"
        );
    }

    #[test]
    fn a_name_that_would_escape_its_path_or_its_line_is_refused() {
        for name in [
            "../../etc/systemd/system/evil",
            "sysg\nExecStart=/bin/sh",
            "sysg/prod",
            "",
            "-sysg",
        ] {
            assert!(
                matches!(check_name(name), Err(Error::NameInvalid(_))),
                "accepted {name:?}"
            );
        }
        assert!(check_name("sysg-prod.api_1").is_ok());
    }

    #[test]
    fn wait_online_is_refused_where_launchd_cannot_honour_it() {
        let mut unit = unit(Scope::System, Manager::Launchd);
        unit.sys = true;
        unit.wait_online = true;
        unit.exe = std::env::current_exe().expect("current exe");
        assert!(matches!(
            unit.check(),
            Err(Error::Unsupported("--wait-online", _))
        ));
    }

    #[test]
    fn a_unit_never_names_a_binary_that_is_not_there() {
        let mut unit = unit(Scope::System, Manager::Systemd);
        unit.sys = true;
        unit.exe = PathBuf::from("/usr/bin/sysg-that-never-was");
        assert!(matches!(unit.check(), Err(Error::ExeMissing(_))));
    }

    #[test]
    fn a_replaced_binary_is_never_written_into_a_unit() {
        assert!(matches!(
            super::running_exe_from(PathBuf::from("/usr/bin/sysg (deleted)")),
            Err(Error::ExeMissing(_))
        ));
    }

    #[test]
    fn a_live_binary_keeps_its_own_path() {
        let exe = std::env::current_exe().expect("current exe");
        assert_eq!(super::running_exe_from(exe.clone()).expect("live"), exe);
    }

    #[test]
    fn only_a_unit_sysg_wrote_may_be_replaced() {
        let dir = tempfile::tempdir().expect("tempdir");
        let ours = dir.path().join("ours.service");
        let theirs = dir.path().join("theirs.service");
        std::fs::write(&ours, unit(Scope::User, Manager::Systemd).render())
            .expect("write");
        std::fs::write(&theirs, "[Service]\nExecStart=/usr/bin/true\n").expect("write");

        assert!(Unit::owns(&ours));
        assert!(!Unit::owns(&theirs));
    }
}
